metadata: {}
pipelines:
  paper:
    envs:
    - host
    path: paper
    stages:
    - build
  terrain:
    envs:
    - host
    path: pipelines/terrain
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
