version: 1
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  paper:
    envs:
      host:
        args: []
    path: paper
    stages:
    - build
  terrain:
    envs:
      host:
        args: []
    path: pipelines/terrain
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
search_sources:
- popperized
