# Sample configuration of data to be parsed for simulation
#---
#random: bool - turn random generator on or off
#randomSeed: int
#numMotes: int
#x_coord: int
#y_coord: int
#terrain: string
---
filename: sim_test_0
random: true
randomSeed: 65432
numMotes: 5
---
filename: sim_test_1
random: true
randomSeed: 87654
numMotes: 2
---
filename: sim_test_2
random: true
randomSeed: 87321
numMotes: 3
